/*
 * Generated by Montru. 
 * Do not edit this file because it might be overwritten.
 */

package dust.mj02.dust.geometry;

import dust.mj02.dust.DustComponents;

public interface DustGeometryComponents extends DustComponents {
	enum DustGeometryTypes implements DustEntityKey { 
		RenderNode, GeometricDimension, ShapePath, ShapeArc, RenderSource, GeometricDataRole, GeometricData, RenderTarget, ShapeComposite, GeometricInclusion, ShapeBox, ShapeRef
	};

	enum DustGeometryAtts implements DustEntityKey { 
		ShapePathClosed, RenderTargetTransformColl
	};

	enum DustGeometryLinks implements DustEntityKey { 
		ShapeArcBegin, ShapeBoxSize, GeometricInclusionTarget, RenderTargetNodeStack, RenderTargetAllShapes, GeometricDataType, GeometricInclusionParameters, ShapeArcEnd, GeometricDataMeasurements, RenderNodeCumulativeRotation
	};

	enum DustGeometryServices implements DustEntityKey { 
		RenderTarget, RenderSource
	};

	enum DustGeometryMessages implements DustEntityKey { 
	};

	enum DustGeometryTags implements DustEntityKey { 
	};

	enum DustGeometryValues implements DustEntityKey { 
		GeometricDimensionCartesianZ, GeometricDimensionCartesianY, GeometricDataRoleRotate, GeometricDimensionCartesianX, GeometricDataRoleLocate, GeometricDataRoleScale
	};
}
